# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_auto_20170523_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location)),
                ('bio', models.TextField(blank=True, null=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='profiles.UserProfile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Location')),
                ('pending', models.ManyToManyField(blank=True, through='profiles.Invite', to='profiles.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='r_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_from', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='invite',
            name='r_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_to', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='intrest',
            field=models.ManyToManyField(to='profiles.Intrest'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='members',
            field=models.ManyToManyField(to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='intrest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Intrest'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('r_from', 'r_to')]),
        ),
    ]
