# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_auto_20170511_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'friends',
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('localization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Localization')),
            ],
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='interst',
            field=models.ManyToManyField(to='profiles.Intrest'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='members',
            field=models.ManyToManyField(to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(related_name='List', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='interst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Intrest'),
        ),
        migrations.AddField(
            model_name='event',
            name='localization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Localization'),
        ),
    ]
