# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
