# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='page-slug'),
        ),
    ]
