# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_groupprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
