# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170529_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='group',
            new_name='name',
        ),
    ]
