# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170516_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='interst',
            new_name='intrest',
        ),
        migrations.RenameField(
            model_name='groupprofile',
            old_name='interst',
            new_name='intrest',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
