# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_groupprofile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=120),
        ),
    ]
