# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
