# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170518_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=2800, null=True),
        ),
    ]
