# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_groupprofile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
