# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_event_cost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freetime',
            unique_together=set([('group', 'user')]),
        ),
    ]
