# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170518_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localization',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='localization',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='localization',
            new_name='location',
        ),
    ]
